#!/bin/bash

/opt/docker/bin/install $MAGENTO_VERSION

service apache2 start > /dev/null 2>&1 &

if [ ! -f /var/log/apache2/error.log ]; then
    touch /var/log/apache2/error.log
fi

tail -f /var/log/apache2/error.log > /dev/stdout &

/opt/docker/bin/watcher /opt/docker/magento/module/ /var/www/ > /dev/null 2>&1
